version: "3.8"
services:

  app:
    image: yanqd0/hugo:0.74.3
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:1313:1313

  util:
    build:
      context: .
      dockerfile: Dockerfile.util
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      TWITTER_CONSUMER_KEY: $TWITTER_CONSUMER_KEY
      TWITTER_CONSUMER_SECRET: $TWITTER_CONSUMER_SECRET
      TWITTER_AUTH_TOKEN: $TWITTER_AUTH_TOKEN
      TWITTER_AUTH_SECRET: $TWITTER_AUTH_SECRET

  im:
    build:
      context: .
      dockerfile: Dockerfile.imagemagick
    working_dir: /app
    volumes:
      - ./:/app
