version: "3.8"
services:

  app:
    image: yanqd0/hugo:0.74.3
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:1313:1313

  util:
    build:
      context: .
      dockerfile: Dockerfile.util
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env

  im:
    build:
      context: .
      dockerfile: Dockerfile.imagemagick
    working_dir: /app
    volumes:
      - ./:/app
