on:
 workflow_dispatch:
 schedule:
  - cron: "0 10 * * *"
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: action
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_AUTH_TOKEN: ${{ secrets.TWITTER_AUTH_TOKEN }}
        TWITTER_AUTH_SECRET: ${{ secrets.TWITTER_AUTH_SECRET }}
      run: |
        docker-compose -f docker-compose.yml run util python ./bin/random-pick.py
        tmp_file=$(mktemp)
        docker-compose -f docker-compose.yml run --volume $tmp_file:/tmp/image-generator.sh util python ./bin/image-generator.py
        docker-compose -f docker-compose.yml run --volume $tmp_file:/tmp/image-generator.sh im ash /tmp/image-generator.sh
        docker-compose -f docker-compose.yml run util python ./bin/tweet.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: todays pick
    - name: build
      run: |
        docker-compose -f docker-compose.yml run app hugo
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
