on:
 workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: action
      run: |
        docker-compose run util python ./bin/random-pick.py
        tmp_file=$(mktemp)
        docker-compose run --volume $tmp_file:/tmp/image-generator.sh util python ./bin/image-generator.py
        docker-compose run --volume $tmp_file:/tmp/image-generator.sh im ash /tmp/image-generator.sh
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: todays pick
    - name: build
      run: |
        docker-compose run app hugo
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
