on:
 workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: action
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_AUTH_TOKEN: ${{ secrets.TWITTER_AUTH_TOKEN }}
        TWITTER_AUTH_SECRET: ${{ secrets.TWITTER_AUTH_SECRET }}
      run: |
        docker-compose -f docker-compose.yml run -e TWITTER_AUTH_TOKEN=$TWITTER_AUTH_TOKEN -e TWITTER_CONSUMER_SECRET=$TWITTER_CONSUMER_SECRET -e TWITTER_AUTH_TOKEN=TWITTER_AUTH_TOKEN -e TWITTER_AUTH_SECRET=TWITTER_AUTH_SECRET util printenv
