on:
 workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: action
      run: |
        docker-compose -f docker-compose.yml run util python ./bin/random-pick.py
        tmp_file=$(mktemp)
        ls -lsa $tmp_file
        chmod 777 $tmp_file
        ls -lsa $tmp_file
        docker-compose -f docker-compose.yml run --volume $tmp_file:/tmp/image-generator.sh util ls -lsa /tmp
        docker-compose -f docker-compose.yml run --volume $tmp_file:/tmp/image-generator.sh util ash -c 'chown root: /tmp/image-generator.sh && python ./bin/image-generator.py'
        docker-compose -f docker-compose.yml run --volume $tmp_file:/tmp/image-generator.sh im ls -lsa /tmp
        docker-compose -f docker-compose.yml run --volume $tmp_file:/tmp/image-generator.sh im ash -c 'chown root: /tmp/image-generator.sh && /tmp/image-generator.sh'
